//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookRent
    {
        public long AutoKey { get; set; }
        public string MemberId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string BookId { get; set; }
        public string CategoryId { get; set; }
        public Nullable<int> NumberOfDay { get; set; }
        public Nullable<int> status { get; set; }
    }
}
